spring:
  datasource:
    url: jdbc:mysql://localhost:3309/todo-buddy-backend-db?serverTimezone=UTC&characterEncoding=UTF-8
    username: dev
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
              enable: true

  data:
    redis:
      host: localhost
      port: 6399

logging.level:
  org.hibernate.SQL: debug # 발생되는 쿼리문을 로그로 출력

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME}
  issuer: ${JWT_ISSUER}

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none