spring:
  config:
    import: 'aws-parameterstore:/config/todobuddy_prod/'
    activate:
      on-profile: prod

  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}

jwt:
  secret-key: ${JWT.SECRET.KEY}
  access-token-expiration-time: ${JWT.ACCESS.EXPIRATION.TIME}
  refresh-token-expiration-time: ${JWT.REFRESH.EXPIRATION.TIME}
  issuer: ${JWT.ISSUER}

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: todobuddy