name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Docker Compose 설치
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: MySQL 및 Redis 설정
        run: docker-compose up -d

      - name: 권한 부여
        run: chmod +x gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -Plocal
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}

      - name: 테스트 로그 출력
        if: failure()
        run: cat build/reports/tests/test/index.html

      - name: 테스트 결과 아티팩트로 저장
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test